/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simulation;

import org.junit.Test;

import com.simulation.Game;

import static org.junit.Assert.*;

public class GameTest {
    @Test public void testSomeLibraryMethod() {
        Game classUnderTest = new Game();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.main(null));
    }
}
